# Dependencies
markdown:         redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            The OpenQuake Engine Blog
tagline:          
url:              http://
paginate:         1
baseurl:          /
author:
  name:           Michele Simionato
  url:            https://github.com/micheles
  email:          michele.simionato@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/micheles/micheles.github.io
pages_list:       
  About: '/about'
  Author: '/author'
  Archive: '/archive'
  Feed: '/atom.xml'
